music/urls.py
from django.conf.urls import url
# importing views
from . import views

app_name = 'music'

urlpatterns = [
    #Default homepage (index)
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    #/music/<album id > /
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    #/music/album/add/
    url(r'^album/add/$', views.AlbumCreate.as_view(), name='album_add'),
    #/music/album/2/
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),
    #/music/album/2/delete
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),

]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

music/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length = 250)
    album_title = models.CharField(max_length=250)
    genre = models.CharField(max_length= 250)
    album_logo = models.CharField(max_length=1000)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + ' = ' + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Album
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import UserForm

###### GENERIC VIEW ######

class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    #model = Album is the same thing as query_set = Album.objects.all and it's the shortcut way of def get_queryset()﻿
    model = Album
    template_name = 'music/detail.html'


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist','album_title','genre','album_logo']

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist','album_title','genre','album_logo']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'
    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name , {'form':form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            #cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            #returns User objects if credientials are correct
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request,user) #this method logs in the user automatically wtf..
                    return redirect('music:index')

        return render(request, self.template_name , {'form':form})






























# from django.shortcuts import render, get_object_or_404
# from .models import Album,Song
#
# def index (request):
#     all_albums = Album.objects.all()
#     context ={
#         'all_albums' : all_albums
#     }
#     return render(request, 'music/index.html', context)
#
# def detail(request, album_id):
#     album = get_object_or_404(Album,pk=album_id)
#     return render(request, 'music/detail.html',{'album' : album})
#
# def favorite(request, album_id):
#     album = get_object_or_404(Album,pk=album_id)
#     try:
#         selected_song = album.song_set.get(pk=request.POST['song'])
#     except (KeyError, Song.DoesNotExist):
#         return render(request,'music/detail.html',{
#         'album': album,
#         'error_message':'you dod not select a valid song',
#         })
#     else:
#         selected_song.is_favorite=True
#         selected_song.save()
#         return render(request, 'music/detail.html',{'album' : album})

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New Album{% endblock %}
{%block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

  <div class="row">

    <div class="col-sm-12 col-md-7">
      <div class="panel panel-default">
        <div class="panel-body">

          <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {% include 'music/form-template.html' %}
              <div class="form-group">
                  <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success">Submit</button>
                  </div>
              </div>
          </form>

        </div>
      </div>
    </div>

  </div>

</div>

{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}MUSI{% endblock %}</title>

  {%load staticfiles %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
  <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <!--logo -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'music:index' %}">MUSI</a>
      </div>
      <!-- Items -->
      <div class="collapse navbar-collapse" id="topNavBar">
        <ul class="nav navbar-nav">
          <li class="">
            <a href="{% url 'music:index' %}">
              <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;&nbsp;
               Albums
            </a>
          </li>
          <li class="">
            <a href="#">
              <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;&nbsp;
               Songs
            </a>
          </li>
        </ul>
        <form class="navbar-form navbar-left" role="search" method="get" action="#">
          <div class="form-group">
            <input type="text" class="form-control" name="q" value="">
          </div>
          <button type="submit" class="btn btn-default">Search</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <a href="{%url 'music:album_add' %}">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;&nbsp;
             Add Album
          </a>
        </li>
        <li class="">
          <a href="#">
            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;&nbsp;
             Logout
          </a>
        </li>
      </ul>
    </div>
  </nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Album details{% endblock %}
{% block body %}
  <img src="{{album.album_logo}}"/>

  <h1>{{album.album_title}}</h1>
  <h3>{{album.artist}}</h3>

    {%for song in album.song_set.all %}
        {{song.song_title}}
        {%if song.is_favorite %}
          <img src="http://i.imgur.com/b9b13Rd.png" />
        {% endif %}
        <br>
      {% endfor %}

{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <span class="text-danger small">{{field.errors}}</span>
    </div>
    <label class="control-label col-sm-2">{{field.label_tag}}</label>
    <div class="col-sm-10">{{field}}</div>
  </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}

    <ul>
      {% for album in all_albums %}
        <li><a href="{% url 'music:detail' album.id %}"> {{album.album_title}} </a>
            <form action="{%url 'music:album-delete' album.id %}">
              {% csrf_token %}
              <input type="submit" value="delete">
            </form>
        </li>
      {% endfor %}
    </ul>

{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %}User registration{% endblock %}

{% block body %}
<div class="container-fluid">

  <div class="row">

    <div class="col-sm-12 col-md-7">
      <div class="panel panel-default">
        <div class="panel-body">

          <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {% include 'music/form-template.html' %}
              <div class="form-group">
                  <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success">Submit</button>
                  </div>
              </div>
          </form>

        </div>
      </div>
    </div>

  </div>

</div>

{% endblock %}